stages:
  - deploy

variables:
  APP_NAME: team-project-7

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: http://172.23.66.241:52091
  only:
    - main
  script:
    - git-push ssh://dokku@172.23.66.241:22/team-project-7